### ISSUE TITLE
Test failure on Windows

### ISSUE THREAD

**Issue by ajalt** [klazuka/intellij-elm#103]
#99 introduced a regression that causes tests to fail on windows.

```
java.lang.AssertionError: 
Expected: [(elm-lang/core, 5.1.1)]
     but: was [(\packages\elm-lang\core, 5.1.1)]
    at org.elm.workspace.ElmWorkspaceTestBase.failure(ElmWorkspaceTestBase.kt:75)
    at org.elm.workspace.ElmWorkspaceTestBase.checkEquals(ElmWorkspaceTestBase.kt:69)
    at org.elm.workspace.ElmWorkspaceServiceTest.test can attach legacy Elm 18 application json files(ElmWorkspaceServiceTest.kt:345)

java.lang.AssertionError: 
Expected: [(elm-lang/core, 5.1.1)]
     but: was [(\packages\elm-lang\core, 5.1.1)]
    at org.elm.workspace.ElmWorkspaceTestBase.failure(ElmWorkspaceTestBase.kt:75)
    at org.elm.workspace.ElmWorkspaceTestBase.checkEquals(ElmWorkspaceTestBase.kt:69)
    at org.elm.workspace.ElmWorkspaceServiceTest.test can attach legacy Elm 18 package json files(ElmWorkspaceServiceTest.kt:449)
```

**Comment by ajalt** [comment]
The plugin has broken a couple of times on windows recently, so it might be a good idea to add a windows CI build. Travis [added windows support](https://blog.travis-ci.com/2018-10-11-windows-early-release) a couple weeks ago. Do you think it would be a good idea to use it instead of (or in addition to) circle ci?

**Comment by klazuka** [comment]
Let's switch to Travis. I was using CircleCI because they were at HeavyBit with us many years ago. But Travis seems simpler and having Windows support would be great.

**Comment by klazuka** [comment]
I'm going to fix the Windows bug and setup Travis right now.

**Comment by ajalt** [comment]
Awesome. When I was looking into travis, it seems like you can install elm from homebrew on osx and chocolaty on windows.

```
os:
  - windows
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];     then brew update           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];     then brew install elm      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install elm     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];   ???                        ; fi
```

The [docs say](https://docs.travis-ci.com/user/reference/windows#supported-languages) that `language: java` isn't supported on windows, but jdk8 _is_ installed, so I think you can still make it work.

**Comment by klazuka** [comment]
Yeah, i saw the same thing about Java. Right now I'm just trying to get the linux build working.

Homebrew looks like it wants to install elm from source since it depends on ghc. But I can also use npm, which I had forgotten about (previously I was downloading the tarball directly because the Elm npm package hadn't yet been updated).

**Comment by klazuka** [comment]
It's turning out to be a real pain to get working. I should have just setup appveyor or something 🙁

**Comment by klazuka** [comment]
I managed to get Travis working, but the Windows builds seem really flaky. It was working well earlier today, but now it's crazy slow. 

I didn't get around to fixing the Windows test failure.
