### ISSUE TITLE
Type inference inspection triggers IntelliJ assertion in ProblemDescriptorBase

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#107]
```
java.lang.Throwable: Assertion failed: ElmValueExpr(VALUE_EXPR)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:163)
	at com.intellij.codeInspection.ProblemDescriptorBase.<init>(ProblemDescriptorBase.java:47)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:94)
	at org.elm.ide.inspections.ElmTypeInferenceInspection$buildVisitor$1.visitElement(ElmTypeInferenceInspection.kt:21)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:276)
```

The assertion that failed is: 
```java
LOG.assertTrue(startContainingFile != null && startContainingFile.isValid() || startElement.isValid(), startElement);
```

from [ProblemDescriptorBase.java#L47](https://github.com/JetBrains/intellij-community/blob/d7e6915a43360168e11615993951d55569ba06bf/platform/analysis-impl/src/com/intellij/codeInspection/ProblemDescriptorBase.java#L47)

Based on the assertion failure message, `startElement` was a `ElmValueExpr(VALUE_EXPR)`, but I unfortunately did not capture the fragment of code that caused this error. I will try to reproduce.

**Comment by klazuka** [comment]
I haven't seen this since then, so I'm going to assume that it's ok.
