### ISSUE TITLE
Can't attach `elm.json` in Windows 10

### ISSUE THREAD

**Issue by jorgengranseth** [klazuka/intellij-elm#136]
Trying to get everything working in Windows 10 I get this:
```
org.elm.workspace.ProjectLoadException: Could not find file C:\Users\<username>\AppData\Roaming\elm\0.19.0\package\NoRedInk\elm-json-decode-pipeline\1.0.0\elm.json
```
when trying to attach the `elm.json` in my project (in a different directory than `C:\Users\...`) on Windows 10.

Log diff in IntelliJ:
```
2018-11-23 15:40:45,828 [  63648]   WARN - .workspace.ElmWorkspaceService - Failed to load C:\<project-path>\elm.json: Could not find file C:\Users\<username>\AppData\Roaming\elm\0.19.0\package\NoRedInk\elm-json-decode-pipeline\1.0.0\elm.json
```

IntelliJ Ultimate version 2018.3 4284.148 (also happened in 2018.2.4 to 2018.2.6) and the last version of the plugin.

I got notified of this stack trace afterwards, which seems related to something-something-windows-7
```
java.lang.NoClassDefFoundError: Could not initialize class com.intellij.ui.Win7TaskBar
	at com.intellij.ui.AppIcon$Win7AppIcon._hideProgress(AppIcon.java:416)
	at com.intellij.ui.AppIcon$BaseIcon.hideProgress(AppIcon.java:104)
	at com.intellij.ui.AppIcon$BaseIcon$1.applicationActivated(AppIcon.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:358)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:347)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:324)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:196)
	at com.sun.proxy.$Proxy104.applicationActivated(Unknown Source)
	at com.intellij.ide.ApplicationActivationStateManager.setActive(ApplicationActivationStateManager.java:122)
	at com.intellij.ide.ApplicationActivationStateManager.updateState(ApplicationActivationStateManager.java:69)
	at com.intellij.ide.IdeEventQueue.processAppActivationEvents(IdeEventQueue.java:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:557)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.SequencedEvent.dispatch(SequencedEvent.java:128)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:698)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:430)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1681)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1630)
	at com.intellij.openapi.ui.messages.MessageDialog.show(MessageDialog.java:181)
	at com.intellij.ui.messages.MessagesServiceImpl.showMessageDialog(MessagesServiceImpl.java:70)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:278)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:294)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:309)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:831)
	at org.elm.workspace.ElmAttachProjectAction$showError$1.run(ElmAttachProjectAction.kt:42)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by klazuka** [comment]
Does the path that fails to load exist on disk? Are there actually any files there? Maybe it exists somewhere else? Do you use the ELM_HOME environment variable?

Does this only happen for the json.decode.pipeline package or does it fail for everything?

The stack trace that you posted at the end seems unrelated—it’s happening during error reporting.

**Comment by jorgengranseth** [comment]
I only get the json.decode.pipeline error, presumably because it's the first package in `elm.json`... And yeah how could I not have checked that it doesn't actually exist! It builds, so I figured it had to exist, but nope - builds on WSL (Windows Subsystem for Linux) but it seems restrictive write access means `node` on Windows can't write to `AppData`. And I can't get IntelliJ to work with WSL.
