### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by prange** [klazuka/intellij-elm#142]
MacOS 10.14.1
IntelliJ IDEA 2018.3 (Ultimate Edition)
Build #IU-183.4284.148, built on November 21, 2018

JRE: 1.8.0_152-release-1343-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1

Plugin version 2.0.3

Steps to reproduce: unknown (yet)

```
java.lang.StackOverflowError
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:593)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:928)
	at com.intellij.psi.impl.source.SpineRef.getGreenStub(SpineRef.java:39)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:374)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getParent(StubBasedPsiElementBase.java:336)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:72)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:53)
	at com.intellij.psi.impl.PsiElementBase.getProject(PsiElementBase.java:214)
	at org.elm.lang.core.resolve.reference.ElmReferenceCached.resolve(ElmReferenceCached.kt:14)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:115)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:80)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.parametricTypeRefType(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:84)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.typeRefType(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression.recordTypeDeclType(TypeExpressionInference.kt:91)
	at org.elm.lang.core.types.TypeExpression.typeAliasDeclarationType(TypeExpressionInference.kt:142)
	at org.elm.lang.core.types.TypeExpression.resolvedTypeRefType(TypeExpressionInference.kt:125)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:120)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:80)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.parametricTypeRefType(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:84)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.typeRefType(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression.recordTypeDeclType(TypeExpressionInference.kt:91)
	at org.elm.lang.core.types.TypeExpression.typeAliasDeclarationType(TypeExpressionInference.kt:142)
	at org.elm.lang.core.types.TypeExpression.resolvedTypeRefType(TypeExpressionInference.kt:125)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:120)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:80)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.parametricTypeRefType(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:84)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.typeRefType(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression.recordTypeDeclType(TypeExpressionInference.kt:91)
	at org.elm.lang.core.types.TypeExpression.typeAliasDeclarationType(TypeExpressionInference.kt:142)
	at org.elm.lang.core.types.TypeExpression.resolvedTypeRefType(TypeExpressionInference.kt:125)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:120)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:80)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.parametricTypeRefType(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:84)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.typeRefType(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression.recordTypeDeclType(TypeExpressionInference.kt:91)
	at org.elm.lang.core.types.TypeExpression.typeAliasDeclarationType(TypeExpressionInference.kt:142)
	at org.elm.lang.core.types.TypeExpression.resolvedTypeRefType(TypeExpressionInference.kt:125)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:120)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:80)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.parametricTypeRefType(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:84)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.typeRefType(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression.recordTypeDeclType(TypeExpressionInference.kt:91)
	at org.elm.lang.core.types.TypeExpression.typeAliasDeclarationType(TypeExpressionInference.kt:142)
	at org.elm.lang.core.types.TypeExpression.resolvedTypeRefType(TypeExpressionInference.kt:125)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:120)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:80)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.parametricTypeRefType(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:84)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.typeRefType(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression.recordTypeDeclType(TypeExpressionInference.kt:91)
	at org.elm.lang.core.types.TypeExpression.typeAliasDeclarationType(TypeExpressionInference.kt:142)
	at org.elm.lang.core.types.TypeExpression.resolvedTypeRefType(TypeExpressionInference.kt:125)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:120)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:80)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.parametricTypeRefType(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:84)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.typeRefType(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression.recordTypeDeclType(TypeExpressionInference.kt:91)
	at org.elm.lang.core.types.TypeExpression.typeAliasDeclarationType(TypeExpressionInference.kt:142)
	at org.elm.lang.core.types.TypeExpression.resolvedTypeRefType(TypeExpressionInference.kt:125)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:120)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:80)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.parametricTypeRefType(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:84)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.typeRefType(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression.recordTypeDeclType(TypeExpressionInference.kt:91)
	at org.elm.lang.core.types.TypeExpression.typeAliasDeclarationType(TypeExpressionInference.kt:142)
	at org.elm.lang.core.types.TypeExpression.resolvedTypeRefType(TypeExpressionInference.kt:125)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:120)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:80)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.parametricTypeRefType(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:84)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.typeRefType(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression.recordTypeDeclType(TypeExpressionInference.kt:91)
	at org.elm.lang.core.types.TypeExpression.typeAliasDeclarationType(TypeExpressionInference.kt:142)
	at org.elm.lang.core.types.TypeExpression.resolvedTypeRefType(TypeExpressionInference.kt:125)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:120)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:80)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.parametricTypeRefType(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:84)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.typeRefType(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression.recordTypeDeclType(TypeExpressionInference.kt:91)
	at org.elm.lang.core.types.TypeExpression.typeAliasDeclarationType(TypeExpressionInference.kt:142)
	at org.elm.lang.core.types.TypeExpression.resolvedTypeRefType(TypeExpressionInference.kt:125)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:120)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:80)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression$parametricTypeRefType$args$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.parametricTypeRefType(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:84)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSeq

...

at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.parametricTypeRefType(TypeExpressionInference.kt:101)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:84)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression$typeRefType$segments$1.invoke(TypeExpressionInference.kt:16)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:691)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:721)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:712)
	at org.elm.lang.core.types.TypeExpression.typeRefType(TypeExpressionInference.kt:68)
	at org.elm.lang.core.types.TypeExpression.recordTypeDeclType(TypeExpressionInference.kt:91)
	at org.elm.lang.core.types.TypeExpression.typeAliasDeclarationType(TypeExpressionInference.kt:142)
	at org.elm.lang.core.types.TypeExpression.resolvedTypeRefType(TypeExpressionInference.kt:125)
	at org.elm.lang.core.types.TypeExpression.upperPathTypeRefType(TypeExpressionInference.kt:120)
	at org.elm.lang.core.types.TypeExpression.typeSignatureDeclType(TypeExpressionInference.kt:80)
	at org.elm.lang.core.types.TypeExpression.access$typeSignatureDeclType(TypeExpressionInference.kt:16)
```

**Comment by klazuka** [comment]
@ajalt looks like an infinite loop in type inference.

**Comment by ajalt** [comment]
I'll get that fixed.

FYI this is an invalid program, so I'll add a diagnostic:

```
This type alias is recursive, forming an infinite type!

8| type alias MonthSection =
              ^^^^^^^^^^^^
When I expand a recursive type alias, it just keeps getting bigger and bigger.
So dealiasing results in an infinitely large type! Try this instead:

    type MonthSection =
        MonthSection
            { prev : Maybe MonthSection }
```
