### ISSUE TITLE
Plugin version 2.0.3 won't start on 2016.3 Idea.

### ISSUE THREAD

**Issue by qeepy** [klazuka/intellij-elm#152]
I have old Idea and this version combo fails with plugin failed to load exception, seems something about plugin api changed inside Idea. Currently on 1.3.2, that is the last that seems work for me. 1.3.3 -> hangs. Sorry if this is a clear wontfix. Great job, this plugin.

**Comment by klazuka** [comment]
If you can post the exception, I would look into whether it can be fixed easily.

**Comment by ajalt** [comment]
Using the the 2016.3 version from [here](https://www.jetbrains.com/idea/download/previous.html), the plugin fails to load:

![capture](https://user-images.githubusercontent.com/1109214/49331814-d0de7580-f557-11e8-8d41-269f3308746a.PNG)

The following appears in the logs, but it's not very enlightening:
```
2018-12-01 10:53:14,155 [  66050]   INFO - roject.impl.ProjectManagerImpl - com.intellij.diagnostic.PluginException:  [Plugin: org.elm.klazuka] 
com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException:  [Plugin: org.elm.klazuka]
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:254)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:519)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:287)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:222)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectWithProgress(ProjectManagerImpl.java:459)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$100(ProjectManagerImpl.java:60)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:406)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:403)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:307)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$11.run(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:572)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.diagnostic.PluginException:  [Plugin: org.elm.klazuka]
	... 27 more
Caused by: java.lang.AbstractMethodError
	at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponentInstance(ComponentManagerImpl.java:427)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.access$300(ComponentManagerImpl.java:58)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:492)
	... 24 more
```

**Comment by qeepy** [comment]
Yeah, I guess this would be pain to maintain this for multiple idea versions.. Is there a mechanism to declare plugin vs idea compatibility..? Just to let idea download the latest version it is compatible with... dunno, never tried if this works.. So far I can live with old versions, thanks guys.

**Comment by klazuka** [comment]
There is a way for plugin’s to declare IntelliJ version compatibility, but I have never paid it much attention. Right now it’s set at 2016.2, so I will bump it up to 2017.x once I figure out the minimal supported version.
