### ISSUE TITLE
Crash on .18 project

### ISSUE THREAD

**Issue by Birowsky** [klazuka/intellij-elm#181]
I got this report in the latest version of the plugin:

```
java.lang.IllegalStateException: should never try to assign <TyMemberRecursiveReference Msg>
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:854)
	at org.elm.lang.core.types.InferenceScope.argumentsAssignable(TypeInference.kt:882)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:849)
	at org.elm.lang.core.types.InferenceScope.argumentsAssignable(TypeInference.kt:882)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:851)
	at org.elm.lang.core.types.InferenceScope.access$assignable(TypeInference.kt:52)
	at org.elm.lang.core.types.InferenceScope$recordAssignable$1.invoke(TypeInference.kt:860)
	at org.elm.lang.core.types.InferenceScope.recordAssignable(TypeInference.kt:869)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:844)
	at org.elm.lang.core.types.InferenceScope.requireAssignable(TypeInference.kt:830)
	at org.elm.lang.core.types.InferenceScope.requireAssignable$default(TypeInference.kt:829)
	at org.elm.lang.core.types.InferenceScope.beginDeclarationInference(TypeInference.kt:111)
	at org.elm.lang.core.types.TypeInferenceKt$inference$1.compute(TypeInference.kt:37)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:88)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:139)
	at org.elm.lang.core.types.TypeInferenceKt.inference(TypeInference.kt:33)
	at org.elm.lang.core.types.TypeInferenceKt.findInference(TypeInference.kt:25)
	at org.elm.ide.inspections.ElmTypeInferenceInspection.getElementDiagnostics(ElmTypeInferenceInspection.kt:12)
	at org.elm.ide.inspections.ElmDiagnosticBasedInspection.visitElement(ElmDiagnosticBasedInspection.kt:10)
	at org.elm.ide.inspections.ElmLocalInspection$buildVisitor$1.visitElement(ElmLocalInspection.kt:17)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$7(LocalInspectionsPass.java:316)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:168)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:110)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$8(LocalInspectionsPass.java:315)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

```
java.lang.IllegalStateException: should never try to assign <TyMemberRecursiveReference Msg>
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:854)
	at org.elm.lang.core.types.InferenceScope.argumentsAssignable(TypeInference.kt:882)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:849)
	at org.elm.lang.core.types.InferenceScope.argumentsAssignable(TypeInference.kt:882)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:851)
	at org.elm.lang.core.types.InferenceScope.access$assignable(TypeInference.kt:52)
	at org.elm.lang.core.types.InferenceScope$recordAssignable$1.invoke(TypeInference.kt:860)
	at org.elm.lang.core.types.InferenceScope.recordAssignable(TypeInference.kt:869)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:844)
	at org.elm.lang.core.types.InferenceScope.requireAssignable(TypeInference.kt:830)
	at org.elm.lang.core.types.InferenceScope.requireAssignable$default(TypeInference.kt:829)
	at org.elm.lang.core.types.InferenceScope.beginDeclarationInference(TypeInference.kt:111)
	at org.elm.lang.core.types.TypeInferenceKt$inference$1.compute(TypeInference.kt:37)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at org.elm.lang.core.types.TypeInferenceKt.inference(TypeInference.kt:33)
	at org.elm.lang.core.types.TypeInferenceKt.findInference(TypeInference.kt:25)
	at org.elm.ide.inspections.ElmTypeInferenceInspection.getElementDiagnostics(ElmTypeInferenceInspection.kt:12)
	at org.elm.ide.inspections.ElmDiagnosticBasedInspection.visitElement(ElmDiagnosticBasedInspection.kt:10)
	at org.elm.ide.inspections.ElmLocalInspection$buildVisitor$1.visitElement(ElmLocalInspection.kt:17)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$7(LocalInspectionsPass.java:316)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:168)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:110)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$8(LocalInspectionsPass.java:315)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

```
Following exceptions happened soon after this one, most probably they are induced.


2018-12-25T09:44:49.916
java.lang.IllegalStateException: should never try to assign <TyMemberRecursiveReference Msg>
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:854)
	at org.elm.lang.core.types.InferenceScope.argumentsAssignable(TypeInference.kt:882)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:849)
	at org.elm.lang.core.types.InferenceScope.argumentsAssignable(TypeInference.kt:882)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:851)
	at org.elm.lang.core.types.InferenceScope.access$assignable(TypeInference.kt:52)
	at org.elm.lang.core.types.InferenceScope$recordAssignable$1.invoke(TypeInference.kt:860)
	at org.elm.lang.core.types.InferenceScope.recordAssignable(TypeInference.kt:869)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:844)
	at org.elm.lang.core.types.InferenceScope.requireAssignable(TypeInference.kt:830)
	at org.elm.lang.core.types.InferenceScope.requireAssignable$default(TypeInference.kt:829)
	at org.elm.lang.core.types.InferenceScope.beginDeclarationInference(TypeInference.kt:111)
	at org.elm.lang.core.types.TypeInferenceKt$inference$1.compute(TypeInference.kt:37)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at org.elm.lang.core.types.TypeInferenceKt.inference(TypeInference.kt:33)
	at org.elm.lang.core.types.TypeInferenceKt.findInference(TypeInference.kt:25)
	at org.elm.ide.inspections.ElmTypeInferenceInspection.getElementDiagnostics(ElmTypeInferenceInspection.kt:12)
	at org.elm.ide.inspections.ElmDiagnosticBasedInspection.visitElement(ElmDiagnosticBasedInspection.kt:10)
	at org.elm.ide.inspections.ElmLocalInspection$buildVisitor$1.visitElement(ElmLocalInspection.kt:17)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$7(LocalInspectionsPass.java:316)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:168)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:110)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$8(LocalInspectionsPass.java:315)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

This is how it looked:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/3199950/50418208-779df500-082a-11e9-8b41-3657f2fed9bc.png">

**Comment by ajalt** [comment]
I'll do my best to reproduce this, but as always, if you're able to post a sample, it would be helpful.

**Comment by klazuka** [comment]
@birowsky i doubt this is a 0.18 bug. Based on the stack trace, it looks like you have some kind of recursive type involving ‘Msg’. I’m sure it’s valid code, but there’s a bug in our plugin that is choking on it. Can you try finding the file with this ‘Msg’ and posting an example?

**Comment by Birowsky** [comment]
@ajalt all my problems arise from my 50K loc project. For anything obvious to isolate, I do so. But in a case like this, I wouldn't know where to start.
@klazuka ah, I have around 70 modules with Msg as a type. Does the stack trace provide a module name?

I'd point out that this happened the first time that I opened the project after updating the plugin. I haven't seen the exception since, but, the plugin seems to be partially working. For example, Show Usages works, but there isn't error for this: `Ok "bla" "bla"`.
