### ISSUE TITLE
Crash when typing `in` in the module decl's exposing list

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#271]
e.g. `module Foo exposing (in`

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at org.elm.lang.core.lexer.ElmLayoutLexerKt.isSingleLineLetIn(ElmLayoutLexer.kt:214)
	at org.elm.lang.core.lexer.ElmLayoutLexerKt.doLayout(ElmLayoutLexer.kt:180)
	at org.elm.lang.core.lexer.ElmLayoutLexerKt.access$doLayout(ElmLayoutLexer.kt:1)
	at org.elm.lang.core.lexer.ElmLayoutLexer.start(ElmLayoutLexer.kt:44)
	at com.intellij.lexer.Lexer.start(Lexer.java:47)
	at com.intellij.lang.impl.TokenSequence$Builder.performLexing(TokenSequence.java:67)
	at com.intellij.lang.impl.PsiBuilderImpl.performLexing(PsiBuilderImpl.java:188)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:161)
	at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:115)
	at com.intellij.lang.impl.PsiBuilderFactoryImpl.createBuilder(PsiBuilderFactoryImpl.java:37)
```

**Comment by ajalt** [comment]
This looks related to #233

**Comment by klazuka** [comment]
From Simon:
> it also happened when I used the renaming tool to rename an already exposed function from `defaultState` to `init`. probably the same bug though :+1:
