### ISSUE TITLE
IllegalArgumentException: can't create a function with no parameters

### ISSUE THREAD

**Issue by atdixon** [klazuka/intellij-elm#276]
```
java.lang.IllegalArgumentException: can't create a function with no parameters
	at org.elm.lang.core.types.TyFunction.<init>(Ty.kt:94)
	at org.elm.lang.core.types.TyFunction.<init>(Ty.kt:91)
	at org.elm.lang.core.types.InferenceScope.inferFunctionCall(TypeInference.kt:291)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:213)
	at org.elm.lang.core.types.InferenceScope.inferAtom(TypeInference.kt:327)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:214)
	at org.elm.lang.core.types.InferenceScope.beginDeclarationInference(TypeInference.kt:114)
	at org.elm.lang.core.types.TypeInferenceKt$inference$1.compute(TypeInference.kt:36)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at org.elm.lang.core.types.TypeInferenceKt.inference(TypeInference.kt:32)
	at org.elm.lang.core.types.TypeInferenceKt.findInference(TypeInference.kt:24)
	at org.elm.ide.inspections.ElmTypeInferenceInspection.getElementDiagnostics(ElmTypeInferenceInspection.kt:13)
	at org.elm.ide.inspections.ElmDiagnosticBasedInspection.visitElement(ElmDiagnosticBasedInspection.kt:10)
	at org.elm.ide.inspections.ElmLocalInspection$buildVisitor$1.visitElement(ElmLocalInspection.kt:17)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
...snip...
```

Reporting exception from IDE. I love this plugin.

**Comment by klazuka** [comment]
Thanks! Receiving these bug reports helps us make the plugin better.
