### ISSUE TITLE
Fix CachedValue warnings in IntelliJ 2019

### ISSUE THREAD

**Issue by klazuka** [klazuka/intellij-elm#365]
```
java.lang.Throwable: Incorrect CachedValue use: same CV with different captured context, this can cause unstable results and invalid PSI access.
Field this$0 in class org.elm.lang.core.resolve.scope.ModuleScope$getDeclaredTypes$1 has non-equivalent values:
  org.elm.lang.core.resolve.scope.ModuleScope@5e58b531 (org.elm.lang.core.resolve.scope.ModuleScope) and
  org.elm.lang.core.resolve.scope.ModuleScope@3a406ec3 (org.elm.lang.core.resolve.scope.ModuleScope)
Either make `equals()` hold for these values, or avoid this dependency, e.g. by extracting CV provider into a static method.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.util.CachedValueStabilityChecker.complain(CachedValueStabilityChecker.java:163)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:134)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:130)
	at com.intellij.util.CachedValueStabilityChecker.checkProvidersEquivalent(CachedValueStabilityChecker.java:87)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:60)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at org.elm.lang.core.resolve.scope.ModuleScope.getDeclaredTypes(ModuleScope.kt:163)
```

```
java.lang.Throwable: Incorrect CachedValue use: same CV with different captured context, this can cause unstable results and invalid PSI access.
Field this$0 in class org.elm.lang.core.resolve.scope.ModuleScope$getDeclaredValues$1 has non-equivalent values:
  org.elm.lang.core.resolve.scope.ModuleScope@3da7d6de (org.elm.lang.core.resolve.scope.ModuleScope) and
  org.elm.lang.core.resolve.scope.ModuleScope@3d6c15d (org.elm.lang.core.resolve.scope.ModuleScope)
Either make `equals()` hold for these values, or avoid this dependency, e.g. by extracting CV provider into a static method.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.util.CachedValueStabilityChecker.complain(CachedValueStabilityChecker.java:163)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:134)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:130)
	at com.intellij.util.CachedValueStabilityChecker.checkProvidersEquivalent(CachedValueStabilityChecker.java:87)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:60)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at org.elm.lang.core.resolve.scope.ModuleScope.getDeclaredValues(ModuleScope.kt:110)
```

```
java.lang.Throwable: Incorrect CachedValue use: same CV with different captured context, this can cause unstable results and invalid PSI access.
Field $activeScopes in class org.elm.lang.core.types.TypeInferenceKt$inference$1 has non-equivalent values:
  [ElmValueDeclaration(VALUE_DECLARATION)] (java.util.LinkedHashSet) and
  [ElmValueDeclaration(VALUE_DECLARATION)] (java.util.LinkedHashSet)
Either make `equals()` hold for these values, or avoid this dependency, e.g. by extracting CV provider into a static method.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.util.CachedValueStabilityChecker.complain(CachedValueStabilityChecker.java:163)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:134)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:130)
	at com.intellij.util.CachedValueStabilityChecker.checkProvidersEquivalent(CachedValueStabilityChecker.java:87)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:60)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at org.elm.lang.core.types.TypeInferenceKt.inference(TypeInference.kt:29)
	at org.elm.lang.core.types.TypeInferenceKt.access$inference(TypeInference.kt:1)
	at org.elm.lang.core.types.InferenceScope.inferReferencedValueDeclaration(TypeInference.kt:591)
	at org.elm.lang.core.types.InferenceScope.inferReferenceElement(TypeInference.kt:532)
	at org.elm.lang.core.types.InferenceScope.inferFieldAccessTarget(TypeInference.kt:388)
	at org.elm.lang.core.types.InferenceScope.inferFieldAccess(TypeInference.kt:361)
	at org.elm.lang.core.types.InferenceScope.inferAtom(TypeInference.kt:329)
	at org.elm.lang.core.types.InferenceScope.inferFunctionCall(TypeInference.kt:297)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:223)
	at org.elm.lang.core.types.InferenceScope.inferAtom(TypeInference.kt:339)
	at org.elm.lang.core.types.InferenceScope.inferFunctionCall(TypeInference.kt:297)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:223)
	at org.elm.lang.core.types.InferenceScope.beginDeclarationInference(TypeInference.kt:115)
	at org.elm.lang.core.types.TypeInferenceKt$inference$1.compute(TypeInference.kt:33)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
```

**Comment by viktor-ferenczi** [comment]
Has just happened while working on compilation errors after a data model change in my project. Similar exception, but different call stack:

```
java.lang.Throwable: Incorrect CachedValue use: same CV with different captured context, this can cause unstable results and invalid PSI access.
Field this$0 in class org.elm.lang.core.resolve.scope.ModuleScope$getVisibleValues$1 has non-equivalent values:
  org.elm.lang.core.resolve.scope.ModuleScope@6bb8cfc1 (org.elm.lang.core.resolve.scope.ModuleScope) and
  org.elm.lang.core.resolve.scope.ModuleScope@5e37c78b (org.elm.lang.core.resolve.scope.ModuleScope)
Either make `equals()` hold for these values, or avoid this dependency, e.g. by extracting CV provider into a static method.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.util.CachedValueStabilityChecker.complain(CachedValueStabilityChecker.java:163)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:134)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:130)
	at com.intellij.util.CachedValueStabilityChecker.checkProvidersEquivalent(CachedValueStabilityChecker.java:87)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:60)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at org.elm.lang.core.resolve.scope.ModuleScope.getVisibleValues(ModuleScope.kt:122)
	at org.elm.lang.core.resolve.scope.ExpressionScope$getVisibleValues$1.invoke(ExpressionScope.kt:21)
	at org.elm.lang.core.resolve.scope.ExpressionScope$getVisibleValues$1.invoke(ExpressionScope.kt:13)
	at org.elm.lang.core.resolve.scope.ExpressionScopeKt.treeWalkUp(ExpressionScope.kt:58)
	at org.elm.lang.core.resolve.scope.ExpressionScope.getVisibleValues(ExpressionScope.kt:19)
	at org.elm.lang.core.resolve.reference.LexicalValueReference.getCandidates(LexicalValueReference.kt:20)
	at org.elm.lang.core.resolve.reference.LexicalValueReference.resolveInner(LexicalValueReference.kt:17)
	at org.elm.lang.core.resolve.reference.ElmReferenceCached$Resolver.resolve(ElmReferenceCached.kt:20)
	at org.elm.lang.core.resolve.reference.ElmReferenceCached$Resolver.resolve(ElmReferenceCached.kt:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:150)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:116)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:149)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:239)
	at org.elm.lang.core.resolve.reference.ElmReferenceCached.resolve(ElmReferenceCached.kt:15)
	at org.elm.lang.core.resolve.reference.ElmReferenceCached.resolve(ElmReferenceCached.kt:8)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:371)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:349)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:223)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:195)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by klazuka** [comment]
Yeah, this happens all the time in the 2019 beta. I’m not sure if it’s a real problem, but I will still fix it. For now, just ignore it.
