### ISSUE TITLE
Exception running elm-format on save

### ISSUE THREAD

**Issue by kennethtiller** [klazuka/intellij-elm#391]
I get the following exception in "IDE Fatal Errors" when elm-format is activated by "Run when files saved?"

 java.lang.Throwable: Assertion failed: Undoable actions allowed inside commands only (see com.intellij.openapi.command.CommandProcessor.executeCommand())
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:180)
	at com.intellij.openapi.command.impl.UndoManagerImpl.undoableActionPerformed(UndoManagerImpl.java:286)
	at com.intellij.openapi.vcs.ex.ChangelistsLocalLineStatusTracker.registerUndoAction(PartialLocalLineStatusTracker.kt:363)
	at com.intellij.openapi.vcs.ex.ChangelistsLocalLineStatusTracker.access$registerUndoAction(PartialLocalLineStatusTracker.kt:92)
	at com.intellij.openapi.vcs.ex.ChangelistsLocalLineStatusTracker$MyUndoDocumentListener.beforeDocumentChange(PartialLocalLineStatusTracker.kt:307)
	at com.intellij.openapi.editor.impl.DocumentImpl.beforeChangedUpdate(DocumentImpl.java:853)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:791)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:661)
	at com.intellij.openapi.editor.impl.DocumentImpl.lambda$setText$2(DocumentImpl.java:1069)
	at com.intellij.openapi.editor.impl.DocumentImpl.setText(DocumentImpl.java:1071)
	at org.elm.workspace.commandLineTools.ElmFormatCLI$formatDocumentAndSetText$writeAction$1$1.run(ElmFormatCLI.kt:58)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at org.elm.workspace.commandLineTools.ElmFormatCLI$formatDocumentAndSetText$writeAction$1.invoke(ElmFormatCLI.kt:57)
	at org.elm.workspace.commandLineTools.ElmFormatCLI$formatDocumentAndSetText$writeAction$1.invoke(ElmFormatCLI.kt:29)
	at org.elm.workspace.commandLineTools.ElmFormatCLIKt$sam$java_lang_Runnable$0.run(ElmFormatCLI.kt)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:377)
	at org.elm.workspace.commandLineTools.ElmFormatCLI.formatDocumentAndSetText(ElmFormatCLI.kt:65)
	at org.elm.ide.components.ElmFormatOnFileSaveComponent$initComponent$1.beforeDocumentSaving(ElmFormatOnFileSaveComponent.kt:46)
	at sun.reflect.GeneratedMethodAccessor925.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:354)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:343)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:318)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:192)
	at com.sun.proxy.$Proxy49.undoTransparentActionStarted(Unknown Source)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:375)
	at org.elm.workspace.commandLineTools.ElmFormatCLI.formatDocumentAndSetText(ElmFormatCLI.kt:65)
	at org.elm.ide.components.ElmFormatOnFileSaveComponent$initComponent$1.beforeDocumentSaving(ElmFormatOnFileSaveComponent.kt:46)
	at sun.reflect.GeneratedMethodAccessor925.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:354)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:343)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:320)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:192)
	at com.sun.proxy.$Proxy27.beforeDocumentSaving(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor925.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.multiCast(FileDocumentManagerImpl.java:142)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$new$0(FileDocumentManagerImpl.java:122)
	at com.sun.proxy.$Proxy27.beforeDocumentSaving(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocumentInWriteAction$4(FileDocumentManagerImpl.java:422)
	at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:400)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocumentInWriteAction(FileDocumentManagerImpl.java:421)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocument$2(FileDocumentManagerImpl.java:383)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:92)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocument(FileDocumentManagerImpl.java:383)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:303)
	at com.intellij.configurationStore.StoreUtilKt$saveDocumentsAndProjectsAndApp$2$1.invokeSuspend(storeUtil.kt:183)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:747)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:696)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by klazuka** [comment]
Which version of IntelliJ are using?

**Comment by sethlivingston** [comment]
I ran into a similar error running elm-format on save on Windows. I fixed the problem by replacing the "auto discovered" path to elm-format's batch command:

C:\Users\me\AppData\Roaming\npm\elm-format.cmd

with the path to the actual executable:

C:\Users\me\AppData\Roaming\npm\node_modules\elm-format\unpacked_bin\elm-format.exe
