### ISSUE TITLE
StackOverflow

### ISSUE THREAD

**Issue by viktor-ferenczi** [klazuka/intellij-elm#395]
Elm plugin 3.1.1

The source file I'm editing is big and deep, I'm not sure yet what caused this:

```
java.lang.StackOverflowError
	at org.elm.lang.core.types.TypeReplacement.replaceUnion(TypeReplacement.kt:91)
	at org.elm.lang.core.types.TypeReplacement.replace(TypeReplacement.kt:66)
	at org.elm.lang.core.types.TypeReplacement.getReplacement(TypeReplacement.kt:129)
	at org.elm.lang.core.types.TypeReplacement.replace(TypeReplacement.kt:62)
	at org.elm.lang.core.types.TypeReplacement.replaceUnion(TypeReplacement.kt:91)
	at org.elm.lang.core.types.TypeReplacement.replace(TypeReplacement.kt:66)
	at org.elm.lang.core.types.TypeReplacement.getReplacement(TypeReplacement.kt:129)
	at org.elm.lang.core.types.TypeReplacement.replace(TypeReplacement.kt:62)
	at org.elm.lang.core.types.TypeReplacement.replaceUnion(TypeReplacement.kt:91)
...
	at org.elm.lang.core.types.TypeReplacement.replaceUnion(TypeReplacement.kt:91)
	at org.elm.lang.core.types.TypeReplacement.replace(TypeReplacement.kt:66)
	at org.elm.lang.core.types.TypeReplacement.getReplacement(TypeReplacement.kt:129)
	at org.elm.lang.core.types.TypeReplacement.replace(TypeReplacement.kt:62)
	at org.elm.lang.core.types.TypeReplacement.replaceUnion(TypeReplacement.kt:91)
	at org.elm.lang.core.types.TypeReplacement.replace(TypeReplacement.kt:66)
	at org.elm.lang.core.types.TypeReplacement.getReplacement(TypeReplacement.kt:129)
	at org.elm.lang.core.types.TypeReplacement.replace(TypeReplacement.kt:62)
```

**Comment by ajalt** [comment]
Thanks for the report. If you can isolate the problem to a self contained program and add it to this issue, I can fix the issue.

**Comment by klazuka** [comment]
Closing due to inactivity.
