### ISSUE TITLE
Null pointer exception when unshelving Elm project

### ISSUE THREAD

**Issue by KasMA1990** [klazuka/intellij-elm#398]
I've created a new Elm project next to an existing one, and I had the new project shelved. When I unshelved it, I got the following exception:

    Unexpected error when loading C:\path\to\elm.json

    java.lang.NullPointerException
        at org.elm.workspace.ElmProject$Companion.parse(ElmProject.kt:106)
        at org.elm.workspace.ElmProject$Companion.parse(ElmProject.kt:85)
        at org.elm.workspace.ElmProject$Companion.parse$default(ElmProject.kt:82)
        at org.elm.workspace.ElmWorkspaceService$asyncLoadProject$1.invoke(ElmWorkspaceService.kt:192)
        at org.elm.workspace.ElmWorkspaceService$asyncLoadProject$1.invoke(ElmWorkspaceService.kt:63)
        at org.elm.utils.FutureKt$runAsyncTask$1.run(future.kt:31)
        at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
        at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

I'm not sure it actually did any harm; I could still navigate around the code, `elm-format` worked fine, etc. But better safe than sorry I guess.

IDEA: 2019.1.1 (Community edition)
Elm plugin: 3.1.1
Windows: 10 Pro 1809

**Comment by klazuka** [comment]
Is this reproducible? I looked at the code and it seems that the only way this would be possible is if your `elm-package.json` file exists but its contents are empty. Is it possible that the file was empty?

**Comment by KasMA1990** [comment]
I just did a new test that reproduced it:

1) Added new folder to this structure:
    topLevelProjectFolder
       |-> existingElmProject1
       |-> existingElmProject2
       |-> newFolderForThisExperiment
       |-> ...

2) ran `elm init` in `newFolderForThisExperiment`, so `elm.json` has the default content
3) Added `Main.elm` in `src` folder with the following code:

    module Main exposing (main)

    main = "hello"

4) Added both `Main.elm` and `elm.json` to git
5) Shelved `Main.elm` and `elm.json`
6) Unshelved them again, and got the error

I don't know if there is a race where the file shows up for the plugin before IDEA has actually populated it with the content it's supposed to have?
