### ISSUE TITLE
StackOverflowError in 3.1.2

### ISSUE THREAD

**Issue by dpinn** [klazuka/intellij-elm#410]
I just upgraded to version 3.1.2. The following error occurs immediately upon editing an Elm file.

```
java.lang.StackOverflowError
	at kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault(Iterables.kt:39)
	at org.elm.lang.core.types.TypeReplacement.replaceUnion(TypeReplacement.kt:147)
	at org.elm.lang.core.types.TypeReplacement.replace(TypeReplacement.kt:66)
	at org.elm.lang.core.types.TypeReplacement.getReplacement(TypeReplacement.kt:129)
	at org.elm.lang.core.types.TypeReplacement.replace(TypeReplacement.kt:62)
	at org.elm.lang.core.types.TypeReplacement.replaceUnion(TypeReplacement.kt:91)
	at org.elm.lang.core.types.TypeReplacement.replace(TypeReplacement.kt:66)
	at org.elm.lang.core.types.TypeReplacement.getReplacement(TypeReplacement.kt:129)
	at org.elm.lang.core.types.TypeReplacement.replace(TypeReplacement.kt:62)
	at org.elm.lang.core.types.TypeReplacement.replaceUnion(TypeReplacement.kt:91)
	at org.elm.lang.core.types.TypeReplacement.replace(TypeReplacement.kt:66)
	at org.elm.lang.core.types.TypeReplacement.getReplacement(TypeReplacement.kt:129)
        ... ad infinitum
```

**Comment by ajalt** [comment]
Thanks for the report. If you can post an example that reproduces this problem, I'll get it fixed.

**Comment by klazuka** [comment]
Closing due to inactivity.
