### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by viktor-ferenczi** [klazuka/intellij-elm#489]
GoLand 2019.2.1
Elm  plugin 3.4.1

Happened while adding a lot of type declarations to definitions inside let statements using Alt-Enter, then selecting the new "Add type annotation" feature. I don't think it has anything to do with the type annotation, this is most likely due to the large number of files changed, then saved by pressing Ctrl-S once at the end.

```
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:751)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:749)
	at org.elm.lang.core.types.RecordFieldReferenceTable.addAll(RecordFieldReferenceTable.kt:23)
	at org.elm.lang.core.types.InferenceScope.recordAssignable(TypeInference.kt:1090)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:1047)
	at org.elm.lang.core.types.InferenceScope.allAssignable(TypeInference.kt:1114)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:1057)
	at org.elm.lang.core.types.InferenceScope.allAssignable(TypeInference.kt:1114)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:1057)
	at org.elm.lang.core.types.InferenceScope.requireAssignable(TypeInference.kt:1000)
	at org.elm.lang.core.types.InferenceScope.requireAssignable$default(TypeInference.kt:994)
	at org.elm.lang.core.types.InferenceScope.inferIfElse(TypeInference.kt:609)
	at org.elm.lang.core.types.InferenceScope.inferAtom(TypeInference.kt:408)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:264)
	at org.elm.lang.core.types.InferenceScope.inferLetIn(TypeInference.kt:523)
	at org.elm.lang.core.types.InferenceScope.inferAtom(TypeInference.kt:398)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:264)
	at org.elm.lang.core.types.InferenceScope.beginDeclarationInference(TypeInference.kt:142)
	at org.elm.lang.core.types.TypeInferenceKt$inference$1.compute(TypeInference.kt:45)
	at org.elm.lang.core.types.TypeInferenceKt$inference$1.compute(TypeInference.kt)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:46)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:93)
	at org.elm.lang.core.types.TypeInferenceKt.inference(TypeInference.kt:41)
	at org.elm.lang.core.types.TypeInferenceKt.findInference(TypeInference.kt:21)
	at org.elm.lang.core.types.TypeInferenceKt.findTy(TypeInference.kt:35)
	at org.elm.lang.core.psi.elements.ElmFieldAccessorFunctionExpr$getReference$1.getTy(ElmFieldAccessorFunctionExpr.kt:31)
	at org.elm.lang.core.resolve.reference.RecordFieldReference.multiResolve(RecordFieldReference.kt:34)
	at org.elm.lang.core.resolve.reference.ElmReferenceBase.multiResolve(ElmReferenceBase.kt:15)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at org.elm.lang.core.resolve.reference.ElmReferenceBase.resolve(ElmReferenceBase.kt:12)
	at org.elm.ide.inspections.ImportVisitor.visitElement(ElmUnusedImportInspection.kt:98)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:297)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:265)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:262)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:262)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by viktor-ferenczi** [comment]
Happened again with Elm 3.4.2. - Could you please reopen this issue?

Yes, I restarted the IDE properly to activate the upgrade.

Issue happened while editing a long type alias containing language translations of about 80 strings and formatting functions. (Language file defined in Elm, my own format.)

**stacktrace.txt**

```
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:751)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:749)
	at org.elm.lang.core.types.RecordFieldReferenceTable.addAll(RecordFieldReferenceTable.kt:20)
	at org.elm.lang.core.types.InferenceScope.recordAssignable(TypeInference.kt:1098)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:1056)
	at org.elm.lang.core.types.InferenceScope.allAssignable(TypeInference.kt:1123)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:1066)
	at org.elm.lang.core.types.InferenceScope.allAssignable(TypeInference.kt:1123)
	at org.elm.lang.core.types.InferenceScope.funcsAssignable(TypeInference.kt:1139)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:1067)
	at org.elm.lang.core.types.InferenceScope.requireAssignable(TypeInference.kt:1006)
	at org.elm.lang.core.types.InferenceScope.requireAssignable$default(TypeInference.kt:1000)
	at org.elm.lang.core.types.InferenceScope$inferBinOpExpr$1.invoke(TypeInference.kt:323)
	at org.elm.lang.core.types.InferenceScope$inferBinOpExpr$1.invoke(TypeInference.kt:319)
	at org.elm.lang.core.types.InferenceScope$inferBinOpExpr$1.invoke(TypeInference.kt:319)
	at org.elm.lang.core.types.InferenceScope.inferBinOpExpr(TypeInference.kt:335)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:274)
	at org.elm.lang.core.types.InferenceScope.beginLetInInference(TypeInference.kt:184)
	at org.elm.lang.core.types.InferenceScope.inferAtom(TypeInference.kt:410)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:276)
	at org.elm.lang.core.types.InferenceScope.beginDeclarationInference(TypeInference.kt:142)
	at org.elm.lang.core.types.TypeInferenceKt$inference$1.compute(TypeInference.kt:46)
	at org.elm.lang.core.types.TypeInferenceKt$inference$1.compute(TypeInference.kt)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:46)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:93)
	at org.elm.lang.core.types.TypeInferenceKt.inference(TypeInference.kt:42)
	at org.elm.lang.core.types.TypeInferenceKt.findInference(TypeInference.kt:22)
	at org.elm.ide.inspections.ElmTypeInferenceInspection.getElementDiagnostics(ElmTypeInferenceInspection.kt:13)
	at org.elm.ide.inspections.ElmDiagnosticBasedInspection.visitElement(ElmDiagnosticBasedInspection.kt:10)
	at org.elm.ide.inspections.ElmLocalInspection$buildVisitor$1.visitElement(ElmLocalInspection.kt:18)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$8(LocalInspectionsPass.java:321)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:169)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$9(LocalInspectionsPass.java:320)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**induced.txt**

```
Following exceptions happened soon after this one, most probably they are induced.


2019-09-12T02:25:45.539
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:751)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:749)
	at org.elm.lang.core.types.RecordFieldReferenceTable.addAll(RecordFieldReferenceTable.kt:20)
	at org.elm.lang.core.types.InferenceScope.recordAssignable(TypeInference.kt:1098)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:1056)
	at org.elm.lang.core.types.InferenceScope.allAssignable(TypeInference.kt:1123)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:1066)
	at org.elm.lang.core.types.InferenceScope.allAssignable(TypeInference.kt:1123)
	at org.elm.lang.core.types.InferenceScope.funcsAssignable(TypeInference.kt:1139)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:1067)
	at org.elm.lang.core.types.InferenceScope.requireAssignable(TypeInference.kt:1006)
	at org.elm.lang.core.types.InferenceScope.requireAssignable$default(TypeInference.kt:1000)
	at org.elm.lang.core.types.InferenceScope$inferBinOpExpr$1.invoke(TypeInference.kt:323)
	at org.elm.lang.core.types.InferenceScope$inferBinOpExpr$1.invoke(TypeInference.kt:319)
	at org.elm.lang.core.types.InferenceScope$inferBinOpExpr$1.invoke(TypeInference.kt:319)
	at org.elm.lang.core.types.InferenceScope.inferBinOpExpr(TypeInference.kt:335)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:274)
	at org.elm.lang.core.types.InferenceScope.beginLetInInference(TypeInference.kt:184)
	at org.elm.lang.core.types.InferenceScope.inferAtom(TypeInference.kt:410)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:276)
	at org.elm.lang.core.types.InferenceScope.beginDeclarationInference(TypeInference.kt:142)
	at org.elm.lang.core.types.TypeInferenceKt$inference$1.compute(TypeInference.kt:46)
	at org.elm.lang.core.types.TypeInferenceKt$inference$1.compute(TypeInference.kt)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:46)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:93)
	at org.elm.lang.core.types.TypeInferenceKt.inference(TypeInference.kt:42)
	at org.elm.lang.core.types.TypeInferenceKt.findInference(TypeInference.kt:22)
	at org.elm.ide.inspections.ElmTypeInferenceInspection.getElementDiagnostics(ElmTypeInferenceInspection.kt:13)
	at org.elm.ide.inspections.ElmDiagnosticBasedInspection.visitElement(ElmDiagnosticBasedInspection.kt:10)
	at org.elm.ide.inspections.ElmLocalInspection$buildVisitor$1.visitElement(ElmLocalInspection.kt:18)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$8(LocalInspectionsPass.java:321)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:169)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$9(LocalInspectionsPass.java:320)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
