### ISSUE TITLE
java.util.ConcurrentModificationException upon save

### ISSUE THREAD

**Issue by z5h** [klazuka/intellij-elm#494]
I made a minor change to a file to retriever the build and somewhere between that and saving I triggered this Exception. The stack trace seemed to differ from another CME, so I'm including this here.

```
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:351)
	at kotlin.collections.CollectionsKt__MutableCollectionsKt.addAll(MutableCollections.kt:124)
	at org.elm.lang.core.types.RecordFieldReferenceTable.addAll(RecordFieldReferenceTable.kt:24)
	at org.elm.lang.core.types.InferenceScope.recordAssignable(TypeInference.kt:1089)
	at org.elm.lang.core.types.InferenceScope.assignable(TypeInference.kt:1047)
	at org.elm.lang.core.types.InferenceScope.requireAssignable(TypeInference.kt:1000)
	at org.elm.lang.core.types.InferenceScope.requireAssignable$default(TypeInference.kt:994)
	at org.elm.lang.core.types.InferenceScope.inferFunctionCall(TypeInference.kt:363)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:263)
	at org.elm.lang.core.types.InferenceScope.inferIfElse(TypeInference.kt:598)
	at org.elm.lang.core.types.InferenceScope.inferAtom(TypeInference.kt:408)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:264)
	at org.elm.lang.core.types.InferenceScope.inferList(TypeInference.kt:576)
	at org.elm.lang.core.types.InferenceScope.inferAtom(TypeInference.kt:409)
	at org.elm.lang.core.types.InferenceScope.inferFunctionCall(TypeInference.kt:342)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:263)
	at org.elm.lang.core.types.InferenceScope.beginCaseBranchInference(TypeInference.kt:182)
	at org.elm.lang.core.types.InferenceScope.inferCase(TypeInference.kt:501)
	at org.elm.lang.core.types.InferenceScope.inferAtom(TypeInference.kt:399)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:264)
	at org.elm.lang.core.types.InferenceScope.inferLetIn(TypeInference.kt:523)
	at org.elm.lang.core.types.InferenceScope.inferAtom(TypeInference.kt:398)
	at org.elm.lang.core.types.InferenceScope.inferExpression(TypeInference.kt:264)
	at org.elm.lang.core.types.InferenceScope.beginDeclarationInference(TypeInference.kt:142)
	at org.elm.lang.core.types.TypeInferenceKt$inference$1.compute(TypeInference.kt:45)
	at org.elm.lang.core.types.TypeInferenceKt$inference$1.compute(TypeInference.kt)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:46)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:93)
	at org.elm.lang.core.types.TypeInferenceKt.inference(TypeInference.kt:41)
	at org.elm.lang.core.types.TypeInferenceKt.findInference(TypeInference.kt:21)
	at org.elm.lang.core.types.TypeInferenceKt.findTy(TypeInference.kt:35)
	at org.elm.lang.core.psi.elements.ElmFieldAccessExpr$getReference$$inlined$fromElement$1.getTy(RecordFieldReference.kt:42)
	at org.elm.lang.core.resolve.reference.RecordFieldReference.multiResolve(RecordFieldReference.kt:34)
	at org.elm.lang.core.resolve.reference.ElmReferenceBase.multiResolve(ElmReferenceBase.kt:15)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at org.elm.lang.core.resolve.reference.ElmReferenceBase.resolve(ElmReferenceBase.kt:12)
	at org.elm.lang.core.resolve.reference.ElmReferenceBase.resolve(ElmReferenceBase.kt:9)
	at org.elm.ide.inspections.ElmUnresolvedReferenceInspection.visitElement(ElmUnresolvedReferenceInspection.kt:38)
	at org.elm.ide.inspections.ElmLocalInspection$buildVisitor$1.visitElement(ElmLocalInspection.kt:18)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:297)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:265)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:262)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:262)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1101)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1687)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1039)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:58)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:58)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:268)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:200)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:119)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by klazuka** [comment]
@ajalt do you think this one would also be fixed by your open PR?
