### ISSUE TITLE
Attaching elm.json gives StackOverflowError

### ISSUE THREAD

**Issue by heinharaldsen** [klazuka/intellij-elm#511]
No matter which elm.json I'm trying this with, I get the following exception:

```
Unexpected error when loading C:\DATA\projects\elm\elm.json

java.lang.StackOverflowError
	at java.base/sun.nio.cs.SingleByte$Encoder.<init>(SingleByte.java:156)
	at java.base/sun.nio.cs.MS1252.newEncoder(MS1252.java:55)
	at java.base/sun.nio.cs.StreamEncoder.<init>(StreamEncoder.java:188)
	at java.base/sun.nio.cs.StreamEncoder.forOutputStreamWriter(StreamEncoder.java:59)
	at java.base/java.io.OutputStreamWriter.<init>(OutputStreamWriter.java:110)
	at java.base/java.io.PrintStream.<init>(PrintStream.java:110)
	at java.base/java.io.PrintStream.<init>(PrintStream.java:148)
	at java.base/java.io.PrintStream.<init>(PrintStream.java:132)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.createBrokenMarkerFile(FSRecords.java:203)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.handleError(FSRecords.java:506)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.access$000(FSRecords.java:153)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readContent(FSRecords.java:1269)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.readContent(PersistentFSImpl.java:222)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getInputStream(PersistentFSImpl.java:560)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.getInputStream(VirtualFileImpl.java:121)
	at org.elm.workspace.ElmProject$Companion.parse(ElmProject.kt:95)
	at org.elm.workspace.ElmProjectKt.loadDependency(ElmProject.kt:252)
	at org.elm.workspace.ElmProjectKt.depsToPackages(ElmProject.kt:231)

```

Example elm.json:

```
{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.0",
    "dependencies": {
        "direct": {
            "elm/browser": "1.0.0",
            "elm/core": "1.0.2",
            "elm/html": "1.0.0"
        },
        "indirect": {
            "elm/json": "1.1.2",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "elm/virtual-dom": "1.0.2"
        }
    },
    "test-dependencies": {
        "direct": {},
        "indirect": {}
    }
}

```
Im using 3.4.2 (same thing happened in 3.4.1) and IntelliJ 2019.2.2 Ultimate Edition

**Comment by heinharaldsen** [comment]
This is probably not an error with the plugin. It was related to this issue, for future reference:

https://github.com/elm/compiler/issues/1797
