### ISSUE TITLE
IncorrectOperationException on trying to complete empty case-of expression

### ISSUE THREAD

**Issue by viktor-ferenczi** [klazuka/intellij-elm#525]
GoLand 2019.2
Elm 0.19
Elm plugin 3.4.3

```
com.intellij.util.IncorrectOperationException
	at com.intellij.psi.impl.CheckUtil.checkWritable(CheckUtil.java:41)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.addRange(SharedImplUtil.java:121)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.addRange(ASTDelegatePsiElement.java:315)
	at org.elm.ide.inspections.MissingCaseBranchAdder.addPatterns(MissingCaseBranchAdder.kt:68)
	at org.elm.ide.inspections.MissingCaseBranchAdder.addMissingBranches(MissingCaseBranchAdder.kt:46)
	at org.elm.ide.inspections.ElmIncompletePatternInspection$visitElement$$inlined$quickFix$1.applyFix(ElmLocalInspection.kt:40)
	at org.elm.ide.inspections.ElmIncompletePatternInspection$visitElement$$inlined$quickFix$1.applyFix(ElmLocalInspection.kt:30)
	at com.intellij.codeInspection.ex.QuickFixWrapper.invoke(QuickFixWrapper.java:73)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:179)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$4(ShowIntentionActionsHandler.java:214)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:92)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:216)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$null$2(ShowIntentionActionsHandler.java:191)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:148)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$3(ShowIntentionActionsHandler.java:190)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:189)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$0(IntentionListStep.java:107)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$13(AbstractPopup.java:1428)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2464)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:222)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:174)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:161)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:58)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1424)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:162)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:318)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:47)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:43)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:135)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:104)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:194)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:104)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:142)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:136)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:132)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:453)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:407)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:348)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:261)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:378)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:358)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:112)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:148)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:93)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:768)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ajalt** [comment]
Can you share the code you were trying to complete, and the types you were trying to complete with?

**Comment by viktor-ferenczi** [comment]
I cannot share the code, but when I see it happening the next time I will try to narrow it down to the simplest case. 

It may be triggered by trying to fill up a case-of expression entered before some original code, for example:

```
[ ...
, case x of

  some original code using x
]
```

It was in a list item when it happened. 

I attempted to fill all cases of the newly entered case-of expression with the intention to move the original code into one of the cases afterwards.

It usually does not work and I have to remove the original code temporarily to let it fill all cases automatically.

I guess the above induced the exception somehow.

**Comment by viktor-ferenczi** [comment]
Triggered again by editing something like:

```elm
Html.div
    [ <attrs> ]
    case status of
         <cases>
```

When I add the <| between the attribute list and the case-of expression then it works. When I remove the <| it fails.
