### ISSUE TITLE
Error: Cyclic service initialization 

### ISSUE THREAD

**Issue by vjrasane** [klazuka/intellij-elm#577]
I've been using intellij-elm plugin in Rider for some time now and so far it's worked great. Today after a machine restart the plugin fails to start. Rider reports the following stactrace:

`com.intellij.diagnostic.PluginException: Cyclic service initialization: ServiceAdapter(descriptor=ServiceDescriptor(interface=org.elm.workspace.ElmWorkspaceService, implementation=org.elm.workspace.ElmWorkspaceService), pluginDescriptor=PluginDescriptor(name=Elm, classpath=/Users/vrasanen/Library/Application Support/Rider2019.3/intellij-elm)) [Plugin: org.elm.klazuka]
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:97)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:288)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:22)
	at org.elm.workspace.ElmWorkspaceServiceKt.getElmWorkspace(ElmWorkspaceService.kt:498)
	at ...`
[elm-plugin-stacktrace.txt](https://github.com/klazuka/intellij-elm/files/4018700/elm-plugin-stacktrace.txt)

Another issue that is most likely related to this and might help solve it is that the plugin no longer finds the elm.json that I previously attached, and when I try to attach it again, I get another error:

> com.elm.workspace.ProjectLoadException:
> Could not load elm-lang/core (5.1.1 = v 6.0.0).
> Is it installed?

I'm using elm version 0.19.1 installed to the project node_modules and the same binary is set in the Rider toolchain settings.

The plugin version is 3.4.1
Rider version is 2019.3.1
Operating system is macOS Mojave 10.14.6

**Comment by vjrasane** [comment]
Also tested this with IntelliJ Idea 2019.3.1 and get the same error

**Comment by klazuka** [comment]
Why would it be trying to load `elm-lang/core` (an Elm 0.18 package) when you are using 0.19.1? Is that expected?

One thing you could try is open `.idea/workspace.xml`, search for `<component name="ElmWorkspace">` and then delete the `project` element inside the `elmProjects` element. Then restart IntelliJ, and hopefully you will be able to re-attach the correct `elm.json`.

Please let me know if that helps.

**Comment by vjrasane** [comment]
That baffles me as well, I've never used Elm 0.18 in this project (or on the same machine, in fact). I don't really understand why its trying to load elm-lang/core.

workspace.xml does contain a component called ElmWorkspace, but the elmProjects tag inside it is completely empty. There is a 'settings' element in the ElmWorkspace, though, that contains the compiler and format path.

Can I add the required project by hand?

**Comment by vjrasane** [comment]
Looks like the issue was solved after I cleared the local elm cache under ~/.elm

Maybe multiple elm versions can confuse the plugin somehow, as I had directories for both 0.19.0 and 0.19.1? After running elm make there's now only directory for 0.19.1 and the plugin attaches the elm.json just fine.

**Comment by r-k-b** [comment]
Clearing `~/.elm` didn't work for me. Happening in Rider 2019.3.1, intellij-elm 3.5.0, in a project with no Elm files.

```
com.intellij.diagnostic.PluginException: Cyclic service initialization: ServiceAdapter(descriptor=ServiceDescriptor(interface=org.elm.workspace.ElmWorkspaceService, implementation=org.elm.workspace.ElmWorkspaceService), pluginDescriptor=PluginDescriptor(name=Elm, classpath=/Users/robertbell/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-0/193.5662.14/Rider.app.plugins/intellij-elm)) [Plugin: org.elm.klazuka]
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:97)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:288)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:22)
	at org.elm.workspace.ElmWorkspaceServiceKt.getElmWorkspace(ElmWorkspaceService.kt:497)
	at org.elm.workspace.ElmAdditionalLibraryRootsProvider.getAdditionalProjectLibraries(ElmAdditionalLibraryRootsProvider.kt:17)
	at com.jetbrains.rider.projectView.indexing.ideaInterop.RiderAdditionalRootsCollector.a(RiderAdditionalRootsCollector.kt:39)
	at com.jetbrains.rider.projectView.indexing.ideaInterop.RiderAdditionalRootsCollector.access$calculateAdditionalRoots(RiderAdditionalRootsCollector.kt:18)
	at com.jetbrains.rider.projectView.indexing.ideaInterop.RiderAdditionalRootsCollector$1.rootsChanged(RiderAdditionalRootsCollector.kt:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:518)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:142)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:438)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:388)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$1(MessageBusImpl.java:241)
	at com.sun.proxy.$Proxy68.rootsChanged(Unknown Source)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.fireRootsChangedEvent(ProjectRootManagerComponent.java:196)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:393)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$200(ProjectRootManagerImpl.java:35)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:93)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:336)
	at org.elm.workspace.ElmWorkspaceService$notifyDidChangeWorkspace$1$$special$$inlined$runWriteAction$1.compute(actions.kt:80)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$11(ApplicationImpl.java:894)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:894)
	at org.elm.workspace.ElmWorkspaceService$notifyDidChangeWorkspace$1.run(ElmWorkspaceService.kt:497)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:519)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:532)
	at org.elm.workspace.ElmWorkspaceService.notifyDidChangeWorkspace(ElmWorkspaceService.kt:421)
	at org.elm.workspace.ElmWorkspaceService.modifyProjects(ElmWorkspaceService.kt:171)
	at org.elm.workspace.ElmWorkspaceService.access$modifyProjects(ElmWorkspaceService.kt:63)
	at org.elm.workspace.ElmWorkspaceService$asyncLoadState$5.apply(ElmWorkspaceService.kt:410)
	at org.elm.workspace.ElmWorkspaceService$asyncLoadState$5.apply(ElmWorkspaceService.kt:63)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at org.elm.workspace.ElmWorkspaceService.asyncLoadState(ElmWorkspaceService.kt:395)
	at org.elm.workspace.ElmWorkspaceService.loadState(ElmWorkspaceService.kt:359)
	at org.elm.workspace.ElmWorkspaceService.loadState(ElmWorkspaceService.kt:63)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:412)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:363)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:130)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:96)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:49)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.kt:258)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:56)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:288)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:22)
	at org.elm.workspace.ElmWorkspaceServiceKt.getElmWorkspace(ElmWorkspaceService.kt:497)
	at org.elm.workspace.ElmAdditionalLibraryRootsProvider.getAdditionalProjectLibraries(ElmAdditionalLibraryRootsProvider.kt:17)
	at com.jetbrains.rider.projectView.indexing.ideaInterop.RiderAdditionalRootsCollector.a(RiderAdditionalRootsCollector.kt:39)
	at com.jetbrains.rider.projectView.indexing.ideaInterop.RiderAdditionalRootsCollector.<init>(RiderAdditionalRootsCollector.kt:27)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:44)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:505)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.createComponents(PlatformComponentManagerImpl.kt:177)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:295)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:315)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProject(ProjectManagerImpl.java:337)
	at com.jetbrains.rider.projectView.SolutionManager.a(SolutionManager.kt:295)
	at com.jetbrains.rider.projectView.SolutionManager.access$openIdeaProject(SolutionManager.kt:38)
	at com.jetbrains.rider.projectView.SolutionManager$openSolution$1.invoke(SolutionManager.kt:224)
	at com.jetbrains.rider.projectView.SolutionManager$openSolution$1.invoke(SolutionManager.kt:38)
	at com.jetbrains.rider.projectView.SolutionManager.a(SolutionManager.kt:250)
	at com.jetbrains.rider.projectView.SolutionManager.openSolution(SolutionManager.kt:222)
	at com.jetbrains.rider.projectView.ideaInterop.RiderRecentProjectsManager.openProject(RiderRecentProjectsManager.kt:67)
	at com.intellij.ide.ReopenProjectAction.actionPerformed(ReopenProjectAction.java:70)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:298)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:149)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:313)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$3.onClick(RecentProjectPanel.java:144)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:846)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:778)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by klazuka** [comment]
I haven't tested on Rider. I'll download it today. In the meantime, can you use IDEA community edition?

**Comment by r-k-b** [comment]
I've downloaded IDEA community edition, but it [doesn't seem to support C# / dotnet development.](https://youtrack.jetbrains.com/issue/RIDER-2715?_ga=2.31882487.895445052.1579900315-1465580712.1565819199) I can still use Rider, nothing bad seems to happen if I ignore the errors from the Elm plugin; it's just distracting.
