### ISSUE TITLE
PyCharm not starting anymore

### ISSUE THREAD

**Issue by c-goes** [klazuka/intellij-elm#598]
I tried installing this plugin via Settings menu. Now PyCharm Professional 2019.3 is not starting anymore.
This error is displayed:

```
Internal error. Please refer to http://jb.gg/ide/critical-startup-errors

java.lang.ExceptionInInitializerError
    at com.intellij.ide.a.i.O.b(O.java:182)
    at com.intellij.ide.a.j.X.a(X.java:544)
    at com.intellij.ide.a.j.X.c(X.java:222)
    at com.intellij.ide.a.j.X.b(X.java:117)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.MainImpl.start(MainImpl.java:94)
    at com.intellij.idea.StartupUtil.lambda$startApp$5(StartupUtil.java:246)
    at com.intellij.util.ui.EdtInvocationManager.executeWithCustomManager(EdtInvocationManager.java:73)
    at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:241)
    at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:213)
    at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:39)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
    at com.intellij.ui.scale.JBUIScale.lambda$static$0(JBUIScale.java:72)
    at com.intellij.openapi.util.AtomicNotNullLazyValue$1.compute(AtomicNotNullLazyValue.java:59)
    at com.intellij.openapi.util.AtomicNotNullLazyValue.getValue(AtomicNotNullLazyValue.java:37)
    at com.intellij.ui.scale.JBUIScale.lambda$static$1(JBUIScale.java:152)
    at com.intellij.util.LazyInitializer$MutableNotNullValue.initialize(LazyInitializer.java:113)
    at com.intellij.util.LazyInitializer$NullableValue.get(LazyInitializer.java:41)
    at com.intellij.util.LazyInitializer$MutableNotNullValue.get(LazyInitializer.java:102)
    at com.intellij.ui.scale.JBUIScale.lambda$static$2(JBUIScale.java:170)
    at com.intellij.util.LazyInitializer$MutableNotNullValue.initialize(LazyInitializer.java:113)
    at com.intellij.util.LazyInitializer$NullableValue.get(LazyInitializer.java:41)
    at com.intellij.util.LazyInitializer$MutableNotNullValue.get(LazyInitializer.java:102)
    at com.intellij.ui.scale.JBUIScale.scale(JBUIScale.java:294)
    at com.intellij.util.ui.JBInsets.create(JBInsets.java:41)
    at com.intellij.util.ui.UIUtil.<clinit>(UIUtil.java:457)
    ... 15 more

-----
JRE 11.0.5+10-b520.17 amd64 by JetBrains s.r.o
/snap/pycharm-professional/176/jbr
```

**Comment by c-goes** [comment]
Was caused by another plugin, sorry!
