### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by dpinn** [klazuka/intellij-elm#709]
I'm seeing multiple instances of NoSuchElementException in Elm plugin v4.9.1. No idea what is triggering them.

```
java.util.NoSuchElementException: Array is empty.
	at kotlin.collections.ArraysKt___ArraysKt.first(_Arrays.kt:836)
	at org.elm.ide.components.ElmFormatOnFileSaveComponent$initComponent$1.beforeDocumentSaving(ElmFormatOnFileSaveComponent.kt:40)
	at jdk.internal.reflect.GeneratedMethodAccessor317.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by klazuka** [comment]
Fixed by #706. Workaround is to disable elm-format-on-save, or just ignore the exception.

The fix is in [version 4.2.0](https://github.com/klazuka/intellij-elm/releases/tag/v4.2.0) which should be appearing on the JetBrains plugin repository in the next day or two. You can also download and install it immediately from the Github release.
