### ISSUE TITLE
Deprecation warning for 'getId'

### ISSUE THREAD

**Issue by karvanit** [klazuka/intellij-elm#776]
Running the Elm plugin in Intellij Ultimate 21.3.2 gives the following warning:

```
com.intellij.diagnostic.PluginException: The default implementation of method 'getId' is deprecated, you need to override it in 'class org.elm.ide.test.run.ElmTestConfigurationFactory'. The default implementation delegates to 'getName' which may be localized, but return value of this method must not depend on current localization. [Plugin: org.elm.klazuka]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:270)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.diagnostic.PluginException.reportDeprecatedDefault(PluginException.java:110)
	at com.intellij.execution.configurations.ConfigurationFactory.getId(ConfigurationFactory.java:75)
	at com.intellij.execution.impl.RunManagerImpl.getFactory(RunManagerImpl.kt:1029)
	at com.intellij.execution.impl.RunManagerImpl.getFactory(RunManagerImpl.kt:1012)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.readExternal(RunnerAndConfigurationSettingsImpl.kt:204)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.readData(RunConfigurationSchemeManager.kt:60)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:43)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:21)
	at com.intellij.configurationStore.LazySchemeProcessor.createScheme$default(scheme-impl.kt:64)
	at com.intellij.configurationStore.schemeManager.SchemeLoader.loadScheme(schemeLoader.kt:177)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl$loadSchemes$isLoadOnlyFromProvider$2.invoke(SchemeManagerImpl.kt:215)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl$loadSchemes$isLoadOnlyFromProvider$2.invoke(SchemeManagerImpl.kt:42)
	at com.intellij.configurationStore.SchemeManagerIprProvider.processChildren(SchemeManagerIprProvider.kt:48)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadSchemes(SchemeManagerImpl.kt:213)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.reload(SchemeManagerImpl.kt:274)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:806)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:69)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:439)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:371)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:123)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:521)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:12)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.compute(ServiceComponentAdapter.kt:41)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:237)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:40)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:595)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:569)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer.serviceCreated(ProjectRunConfigurationInitializer.kt:28)
	at com.intellij.openapi.project.impl.ProjectExImpl$init$$inlined$runOnlyCorePluginExtensions$1.accept(projectLoader.kt:92)
	at com.intellij.openapi.project.impl.ProjectExImpl$init$$inlined$runOnlyCorePluginExtensions$1.accept(projectLoader.kt)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:299)
	at com.intellij.openapi.project.impl.ProjectExImpl.init(ProjectExImpl.kt:290)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:179)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:272)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.access$prepareProject(ProjectManagerExImpl.kt:59)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:121)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:59)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:94)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by Confidenceman02** [comment]
Yep seeing this also. Everything still seems to run fine if I ignore it however.

**Comment by fanf** [comment]
Hi, I'm seing it, too, and I was wondering if anybody knows how to avoid the red notification popup in intellij until it's corrected. Everything seems to work fine appart that extremely intrusive notification: 
![image](https://user-images.githubusercontent.com/44649/147124337-3e57deda-a1fd-4561-9d52-8c99168f147a.png)
(closing it to have ti repoping after a couple of minutes feels like not being the correct workaround)

**Comment by code-sur** [comment]
same issue here with **Elm plugin 4.4.1** with **WebStorm 2021.3**

**Comment by smoli** [comment]
@fanf I clicked "See details" and then "Clear all". At least in my current session the popup didn't appear since

**Comment by fanf** [comment]
@smoli stange, I tested that and on my case, it reappear regularly (I was not able to understand what triggers it though)

**Comment by smoli** [comment]
Yes. In the end the message reappeared for me too. But it didn’t for quite some time. I suppose only specific actions involving elm trigger the message and I didn’t do any of them.

**Comment by fetsh-edu** [comment]
@klazuka Would it be sufficient to add this line to to [ElmTestConfigurationFactory.kt](https://github.com/klazuka/intellij-elm/blob/eafbfe8ffa8d2758de6a4da8c7233af02d14babd/src/main/kotlin/org/elm/ide/test/run/ElmTestConfigurationFactory.kt) to resolve this issue?
```kotlin
override fun getId() = "ELM_TEST_RUN_CONFIGURATION_FACTORY"
```

**Comment by marciofrayze** [comment]
Having the same issue here on MacOS 12.1.2 and IntelliJ CE 2021.3.2. Anyone found a workaround/fix for this problem?

**Comment by nilskuhn** [comment]
Same here on linux:
IntelliJ IDEA 2021.3.2
Build #IU-213.6777.52, built on January 28, 2022

**Comment by MagdaKadlubowska** [comment]
I'm still encountering this issue: on WebStorm 2022.2.1 as well as PhpStorm 2022.2.1 and Pycharm 2022.2... all running on Fedora 34.

**Comment by AlexandreHerbreteau** [comment]
Me too, still having the same issue. One year after the release of the 4.4.1, when the 4.4.2 will come out to fix this bug ? 
Thanks.

**Comment by mnugter** [comment]
And me too, I still have the issue with the lastest versions.

**Comment by RomanistHere** [comment]
There is an option to dismiss popup with error.

However, we're developers, aren't we? Can't someone with knowlegde of how plugins work fork this project and add this `getId` method to make error disappear?

**Comment by cies** [comment]
This is part of the v5 release that will soon be (pre-)released on the marketplace in a new organization. 
We'll close this issue when it has proven to work.

**Comment by cies** [comment]
It seems to be fixed in v5.

It's not yet on the Marketplace, but in the README of this project you find the instructions for installing is manually. Download it here:

https://github.com/intellij-elm/intellij-elm/releases/tag/5.0.0-beta26

**Comment by frankbe** [comment]
The error no longer occurs in the new version. Great to see this seems to be solved!
