### ISSUE TITLE
The default implementation of method 'getId' is deprecated

### ISSUE THREAD

**Issue by smucode** [klazuka/intellij-elm#782]
After installing the latest intellij community edition for apple silicon i'm getting this warning from time to time. Things seem to work, just a bit annoying.

```
com.intellij.diagnostic.PluginException: The default implementation of method 'getId' is deprecated, you need to override it in 'class org.elm.ide.test.run.ElmTestConfigurationFactory'. The default implementation delegates to 'getName' which may be localized, but return value of this method must not depend on current localization. [Plugin: org.elm.klazuka]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:290)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.diagnostic.PluginException.reportDeprecatedDefault(PluginException.java:110)
	at com.intellij.execution.configurations.ConfigurationFactory.getId(ConfigurationFactory.java:75)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.getName(RunnerAndConfigurationSettingsImpl.kt:154)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.getSchemeKey(RunConfigurationSchemeManager.kt:37)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.getSchemeKey(RunConfigurationSchemeManager.kt:21)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.isRenamed(SchemeManagerImpl.kt:531)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.save(SchemeManagerImpl.kt:327)
	at com.intellij.configurationStore.Scheme_implKt.save(scheme-impl.kt:164)
	at com.intellij.execution.impl.RunManagerImpl.getState(RunManagerImpl.kt:625)
	at com.intellij.execution.impl.RunManagerImpl.getState(RunManagerImpl.kt:69)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponent(ComponentStoreImpl.kt:332)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreImpl.kt:238)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreWithExtraComponents.kt:95)
	at com.intellij.configurationStore.ComponentStoreImpl$commitComponentsOnEdt$$inlined$withEdtContext$intellij_platform_configurationStore_impl$1.invokeSuspend(ComponentStoreImpl.kt:719)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion$scheduleWithinConstraints$1.invoke(BaseConstrainedExecution.kt:68)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion.scheduleWithinConstraints(BaseConstrainedExecution.kt:71)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution.scheduleWithinConstraints(BaseConstrainedExecution.kt:38)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl.access$scheduleWithinConstraints$s1153900543(BaseExpirableExecutorMixinImpl.kt:12)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl$scheduleWithinConstraints$$inlined$Runnable$1.run(Runnable.kt:19)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by naimdjon** [comment]
This is really annoying and made me switch to VS code. Is there a fix for this which can be manually applied?

**Comment by smucode** [comment]
Looks like it's fixed, just need to wait for the release https://github.com/klazuka/intellij-elm/commit/83e20f0e6d7f0136cb02bee233ac538b82a3673f

**Comment by denizdogan** [comment]
Anything stopping this fix from being released? It's quite annoying.

**Comment by denizdogan** [comment]
Looks like there's a massive overhaul of the entire plugin in the works based on recent commits :)

**Comment by ShebangDog** [comment]
@naimdjon 
@denizdogan 
If you want to use the modified plugin, you can do so by following these steps
1. Clone this project and build it to obtain a jar file.
Gradle -> Elm Intellij -> Tasks -> build -> build(select and run gradle task)
![image](https://user-images.githubusercontent.com/38370581/162728879-428ad86f-6f7c-44c5-83b1-8eacd41d476c.png)

and then, Gradle build jar file
![image](https://user-images.githubusercontent.com/38370581/162728655-8ec1999c-7bef-469c-b0d4-6b9e2f84cc06.png)


2. You can then apply this plugin to IntellijIdea to use the modified plugin
Preferences -> Plugin -> Setting (Setting Icon) -> install plugin from disk
and then, select your built jar file (hogehoge-elm-plugin.jar)
![image](https://user-images.githubusercontent.com/38370581/162727291-fd41a7f3-5771-43d2-b525-fe8725349894.png)

**Comment by jackgene** [comment]
> @naimdjon @denizdogan If you want to use the modified plugin, you can do so by following these steps
> 
> 1. Clone this project and build it to obtain a jar file.
>    Gradle -> Elm Intellij -> Tasks -> build -> build(select and run gradle task)
>    ![image](https://user-images.githubusercontent.com/38370581/162728879-428ad86f-6f7c-44c5-83b1-8eacd41d476c.png)
> 
> and then, Gradle build jar file ![image](https://user-images.githubusercontent.com/38370581/162728655-8ec1999c-7bef-469c-b0d4-6b9e2f84cc06.png)
> 
> 2. You can then apply this plugin to IntellijIdea to use the modified plugin
>    Preferences -> Plugin -> Setting (Setting Icon) -> install plugin from disk
>    and then, select your built jar file (hogehoge-elm-plugin.jar)
>    ![image](https://user-images.githubusercontent.com/38370581/162727291-fd41a7f3-5771-43d2-b525-fe8725349894.png)

Thank you for this. I wanted to mention that for IDEA 2022.1, I had to update `gradle.properties`, replacing:

```pluginUntilBuild = 213.*
```

With:
```pluginUntilBuild = 221.*
```

**Comment by kamil7x** [comment]
@klazuka could you release fixed version, please?

**Comment by raphaelpereira** [comment]
+1

Please @klazuka could you create a release? This problem is very annoying and the work around requires a full local build.

**Comment by marperia** [comment]
Seriously, it's been awhile since problem occurred. I still have it in 2023...

**Comment by boxed** [comment]
Maybe you could enable someone else to make a release?

**Comment by imor** [comment]
@klazuka could you please make a release with the fix.

**Comment by frontmesh** [comment]
> @naimdjon @denizdogan If you want to use the modified plugin, you can do so by following these steps
> 
> 1. Clone this project and build it to obtain a jar file.
>    Gradle -> Elm Intellij -> Tasks -> build -> build(select and run gradle task)
>    ![image](https://user-images.githubusercontent.com/38370581/162728879-428ad86f-6f7c-44c5-83b1-8eacd41d476c.png)
> 
> and then, Gradle build jar file ![image](https://user-images.githubusercontent.com/38370581/162728655-8ec1999c-7bef-469c-b0d4-6b9e2f84cc06.png)
> 
> 2. You can then apply this plugin to IntellijIdea to use the modified plugin
>    Preferences -> Plugin -> Setting (Setting Icon) -> install plugin from disk
>    and then, select your built jar file (hogehoge-elm-plugin.jar)
>    ![image](https://user-images.githubusercontent.com/38370581/162727291-fd41a7f3-5771-43d2-b525-fe8725349894.png)

it is currently not compatible with the latest version of IntellijIdea community edition. :/

**Comment by cies** [comment]
The releases distributed on Github should fix this issue. See them here (5.0.0-betaX and newer): https://github.com/intellij-elm/intellij-elm/releases

Could someone confirm this fixed the issue, so we can close this...

We're still working to get a new Elm plugin on the Marketplace (last open problem preventing it to land in the Marketplace can be found in #813)

**Comment by MaicolBen** [comment]
I can confirm is fixed!
