### ISSUE TITLE
Current IntelliJ version is not supported by 5.0.0 and higher

### ISSUE THREAD

**Issue by ahankinson** [klazuka/intellij-elm#832]
### What happened?

If you upgrade to IntelliJ 2024.2.X then the last available plugin version is 5.0.0-beta27. All subsequent releases have a version constraint that they will only work until 2024.1.6. 

https://plugins.jetbrains.com/plugin/24075-elm/versions

Unfortunately there are some bugs that were present in beta27 that are fixed in later versions, but they are not available. 

### Steps to reproduce

Try to install a later version and IntelliJ will complain that it is not supported. 

### IntelliJ IDE details (should contain the Elm plugin version and OS details)

IntelliJ 2024.2 and higher.

**Comment by kantuni** [comment]
Same here. This is the error message that I get

```
Unexpected error when loading /Users/Henrikh/Desktop/feedbackone/dashboard/elm.json

com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "null" (in directory "/private/var/folders/rh/w_3p78110j9_zkm3x2gf0g700000gn/T/elm_deps_hack2"): error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:384)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:21)
	at org.elm.openapiext.SubprocessesKt.execute(Subprocesses.kt:74)
	at org.elm.openapiext.SubprocessesKt.execute$default(Subprocesses.kt:54)
	at org.elm.workspace.commandLineTools.LamderaCLI.make(LamderaCLI.kt:35)
	at org.elm.workspace.commandLineTools.LamderaCLI.make$default(LamderaCLI.kt:22)
	at org.elm.workspace.ElmWorkspaceService.installProjectDeps(ElmWorkspaceService.kt:283)
	at org.elm.workspace.ElmWorkspaceService.access$installProjectDeps(ElmWorkspaceService.kt:65)
	at org.elm.workspace.ElmWorkspaceService$asyncLoadProject$1.invoke(ElmWorkspaceService.kt:207)
	at org.elm.workspace.ElmWorkspaceService$asyncLoadProject$1.invoke(ElmWorkspaceService.kt:199)
	at org.elm.utils.FutureKt$runAsyncTask$1.run(future.kt:31)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:103)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:103)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:109)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:103)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Cannot run program "null" (in directory "/private/var/folders/rh/w_3p78110j9_zkm3x2gf0g700000gn/T/elm_deps_hack2"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:463)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:469)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:374)
	... 42 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:295)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:225)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
	... 46 more

```

**Comment by kantuni** [comment]
The workaround mentioned [here](https://github.com/intellij-elm/intellij-elm/issues/828#issuecomment-2155308129) worked perfectly!

**Comment by ahankinson** [comment]
You can also just add `true` to this, which will always return a success value.
